KnowledgeTesting/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model = KnowledgeModel;


namespace KnowledgeTesting.Controllers
{
    public class HomeController : Controller
    {
        Model.Manager manager = new Model.Manager(MvcApplication.DataProvider);

        // GET: Home
        public ActionResult Index()
        {
            Session["UserName"] = null;

            ViewBag.UserNames = manager.GetUsers().Select(u => u.UserName).ToArray();

            return View();
        }

        [HttpPost]
        public ActionResult Index(string userName)
        {
            return View("Test", manager.GetUser(userName));
        }
    }
}

KnowledgeTesting/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model = KnowledgeModel;

namespace KnowledgeTesting.Controllers
{
    public class TestController : Controller
    {
        Model.Manager manager = new Model.Manager(MvcApplication.DataProvider);

        string UserName
        {
            get
            {
                if (Session["UserName"] != null)
                {
                    return Session["UserName"].ToString();
                }

                return "";
            }
            set
            {
                Session["UserName"] = value;
            }
        }



        public ActionResult Index(string UserName)
        {
            if (!string.IsNullOrEmpty( UserName))
            {
                this.UserName = UserName;
            
                Model.Test test = manager.CreateTest(UserName);

                return View(test);
            }

            return RedirectToAction("Index", "Home");
        }


        public ActionResult Started(string AnswerText)
        {
            string userName = this.UserName;

            if (userName != "")
            {
                Model.Test test = manager.GetTest(userName);

                if (!test.IsFinished)
                {
                    if (test.IsNew)
                    {
                        test.Start();
                    }
                    else if (test.IsStarted)
                    {
                        if (!string.IsNullOrEmpty(AnswerText))
                        {
                            if (AnswerText != "Next")
                            {
                                Model.Answer answer = test.CurrentQuestion.GetAnswers().FirstOrDefault(a => a.AnswerText == AnswerText);

                                if (answer != null)
                                {
                                    test.SetAnswer(answer);
                                }
                            }

                            test.NextQuestion();
                        }
                    }

                    if (!test.IsFinished)
                    {
                        return View(test);
                    }
                    else
                    {
                        return RedirectToAction("Finished");
                    }
                }
            }

            return RedirectToAction("Index", "Home");
        }

        public ActionResult Next()
        {
            return RedirectToAction("Started", new { AnswerText = "Next" });
        }

        public ActionResult Finished()
        {
            string userName = this.UserName;

            if (userName != "")
            {
                Model.Test test = manager.GetTest(userName);

                if (test.IsFinished)
                {
                    return View(test);
                }
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

KnowledgeTesting/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model = KnowledgeModel;

namespace KnowledgeTesting.Controllers
{
    public class UserController : Controller
    {
        Model.Manager manager = new Model.Manager(MvcApplication.DataProvider);

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Registration(string UserName)
        {
            if (!string.IsNullOrEmpty(UserName))
            {
                var user = manager.CreateUser(UserName);

                if (user.Exists)
                {
                    return View(user);
                }
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

KnowledgeTesting/Views/Home/Index.cshtml
<h2>Тестирование знаний</h2>

<br />

@if (ViewBag.UserNames.Length > 0)
{
    using (Html.BeginForm("Index", "Test"))
    {
        <p>Выберете ваше имя:</p>
        @Html.DropDownList("UserName", new SelectList(ViewBag.UserNames), new { @class = "chosen-select form-control" });
        <br />
        <input type="submit" value="Перейти к тестированию" class="btn btn-default" />
    }
}

<br />

@Html.ActionLink("Регистрация нового пользователя", "Index", "User")

KnowledgeTesting/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("В начало", "Index", "Home")</li>
                </ul>
                @*<p class="nav navbar-text navbar-right">@User.Identity.Name</p>*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>© 2017. Приложение разработано для ООО «Тюменский нефтяной научный центр»</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

KnowledgeTesting/Views/Test/Finished.cshtml
@model KnowledgeModel.Test

@if (Model != null)
{

<h2>Тестирование завершено!</h2>

<br />

<h3>Набрано баллов: <b>@Model.ResultMark</b> </h3>

<br />

<h3>@Model.ResultTitle</h3>

<hr />

<p>@Model.ResultDescription</p>

}

KnowledgeTesting/Views/Test/Index.cshtml
@model KnowledgeModel.Test

@if (Model != null && Model.IsNew)
{
    using (Html.BeginForm("Started", "Test"))
    {
    <h3>Имя тестируемого: @Model.User.UserName</h3>
    <br />

    <h2>Всё готово для начала тестирования!</h2>
    

    <br />
    <p>
        Вам будет задано @Model.QuestionMax вопросов. Для зачета результатов необходимо правильно ответить мимнимум на @Model.QuestionMinCorrectAnswer вопросов. 
    </p>
    <br />
    <p>
        Соберитесь с мыслями и приступайте... Удачи!
    </p>
    <br />
    <input type="submit" value="Начать тестировние" class="btn btn-default" />
    }
}

KnowledgeTesting/Views/Test/Started.cshtml
@model KnowledgeModel.Test

@if (Model != null)
{

    using (Html.BeginForm())
    {
    <h2>Вопрос № @Model.CurrentQuestionNumber</h2>

    <h3>
        @Model.CurrentQuestion.QuestionText
    </h3>


        foreach (var answer in Model.CurrentQuestion.GetAnswers())
        {
        <p>
            @Html.RadioButton("AnswerText", answer.AnswerText)
            @answer.AnswerText
        </p>
        }

    <input type="submit" value="Ответить" class="btn btn-default" />
    
    }
    @*using (Html.BeginForm())
    {
    <input type="submit" value="Пропустить" class="btn btn-default" />
    }*@

    <br />

    @Html.ActionLink("Пропустить", "Next", "Test")
}

KnowledgeTesting/Views/User/Index.cshtml
@using (Html.BeginForm("Registration", "User")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h2>Регистрация пользователя</h2>
        <br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <p>Введите ваше имя:</p>
            @Html.Editor("UserName", new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessage("UserName", "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <input type="submit" value="Зарегистрироваться" class="btn btn-default" />
            @Html.ActionLink("Отмена", "Index", "Home")
        </div>
    </div>
}

KnowledgeTesting/Views/User/Registration.cshtml
@model KnowledgeModel.User

@if (Model != null && Model.Exists)
{
    using (Html.BeginForm("Index", "Test", new { UserName = Model.UserName }, FormMethod.Post))
    {

    <h2>Регистрация прошла успешно!</h2>
    <br />

    <div class="dl-horizontal">
        Ваше имя:
        <h3>@Html.DisplayFor(model => model.UserName)</h3>
    </div>

    <br />

    <input type="submit" value="Перейти к тестированию" class="btn btn-default" />
    }
}